import './globals.css';
import { Roboto } from 'next/font/google';
import SvgGlobalSprite from './SvgGlobalSprite';

export const metadata = {
	title: 'Weather App',
	description: 'Generated by create next app',
};

const roboto = Roboto({
	weight: ['400', '700'],
	subsets: ['latin'],
	display: 'swap',
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={roboto.className}>
			<body>
				<SvgGlobalSprite />
				{children}
			</body>
		</html>
	);
}
