import './globals.css';
import SvgGlobalSprite from './SvgGlobalSprite';

export const metadata = {
	title: 'Weather App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<SvgGlobalSprite />
				{children}
			</body>
		</html>
	);
}
